// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ward27EmploymentRegistry.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215134715_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PhysicalAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhysicalAddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid?>("PhysicalAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhysicalAddressId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Device")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncodedToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("AspNetRefreshTokens");
                });

            modelBuilder.Entity("Domain.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00edafe3-b047-5980-d0fa-da10f400c1e5"),
                            ConcurrencyStamp = "58e9c747-0189-4088-b3c4-d1752dd3304f",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075"),
                            ConcurrencyStamp = "7badeb99-5b7e-479a-acea-4dccef342d03",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApplicationDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CompensationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationInDays")
                        .HasColumnType("int");

                    b.Property<Guid?>("EmployerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<int?>("MinimumExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("PositionsAvailable")
                        .HasColumnType("int");

                    b.Property<int>("PositionsFilled")
                        .HasColumnType("int");

                    b.Property<Guid>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequiredSkills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.Property<string>("WorkLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("WorkLocationAddressId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.HasIndex("PostedByUserId");

                    b.HasIndex("WorkLocationAddressId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("Domain.Entities.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobApplications");
                });

            modelBuilder.Entity("Domain.Entities.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedA")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("JobAssignments");
                });

            modelBuilder.Entity("Domain.Entities.PhysicalAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Suburb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PhysicalAddresses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1c03637-213a-4fad-bcba-a572988e57f7"),
                            AdditionalDetails = "Flat 20",
                            City = "Rustenburg",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 2, 15, 13, 47, 13, 836, DateTimeKind.Utc).AddTicks(1925),
                            IsDeleted = false,
                            Latitude = -29.9116,
                            Longitude = 23.767099999999999,
                            PostalCode = "7988",
                            Province = "Eastern Cape",
                            StreetName = "Mhlongo Street",
                            Suburb = "Bedfordshire"
                        },
                        new
                        {
                            Id = new Guid("a0ee568b-8bf2-41a5-a3d9-a2d4d393d66e"),
                            City = "Kimberley",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 2, 15, 13, 47, 13, 837, DateTimeKind.Utc).AddTicks(2623),
                            IsDeleted = false,
                            Latitude = -23.245200000000001,
                            Longitude = 25.640999999999998,
                            PostalCode = "9201",
                            Province = "Eastern Cape",
                            StreetName = "Dlamini Street",
                            StreetNumber = "9448",
                            Suburb = "Berkshire"
                        },
                        new
                        {
                            Id = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            City = "Port Elizabeth",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 2, 15, 13, 47, 13, 837, DateTimeKind.Utc).AddTicks(2695),
                            IsDeleted = false,
                            Latitude = -32.864600000000003,
                            Longitude = 26.545500000000001,
                            PostalCode = "6759",
                            Province = "Eastern Cape",
                            StreetName = "Brown Street",
                            StreetNumber = "6068",
                            Suburb = "Berkshire"
                        },
                        new
                        {
                            Id = new Guid("86bbe442-1d6a-4f8a-9f2b-72dc6bb926e5"),
                            City = "Rustenburg",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 2, 15, 13, 47, 13, 837, DateTimeKind.Utc).AddTicks(2758),
                            IsDeleted = false,
                            Latitude = -28.322500000000002,
                            Longitude = 31.060300000000002,
                            PostalCode = "7795",
                            Province = "Eastern Cape",
                            StreetName = "Heller Street",
                            StreetNumber = "1315",
                            Suburb = "Buckinghamshire"
                        },
                        new
                        {
                            Id = new Guid("c230c7d4-7c47-48bb-b319-13701cc8c52a"),
                            City = "Pietermaritzburg",
                            Country = "South Africa",
                            CreatedAt = new DateTime(2026, 2, 15, 13, 47, 13, 837, DateTimeKind.Utc).AddTicks(2812),
                            IsDeleted = false,
                            Latitude = -27.3703,
                            Longitude = 32.398800000000001,
                            PostalCode = "4910",
                            Province = "Eastern Cape",
                            StreetName = "Moore Street",
                            StreetNumber = "6747",
                            Suburb = "Buckinghamshire"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AltText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("AspectRatio")
                        .HasColumnType("float");

                    b.Property<string>("AudioCodec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BitRate")
                        .HasColumnType("int");

                    b.Property<string>("CloudinaryAssetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryFolder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryResourceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinarySecureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloudinaryVersion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("float");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("float");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResourceType")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VideoCodec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("VerifiedByUserId");

                    b.ToTable("Resources");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Administrator", b =>
                {
                    b.HasBaseType("Domain.Entities.Identity.ApplicationUser");

                    b.HasDiscriminator().HasValue("Administrator");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd6ebe91-e83e-42e1-be3e-07ba2f25236b"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "34d67e91-4c5a-4875-97d0-4c096fcecf40",
                            Email = "syavuya08@outlook.com",
                            EmailConfirmed = true,
                            FirstName = "Siyavuya",
                            Gender = 1,
                            LastName = "Chagi",
                            LockoutEnabled = false,
                            NormalizedEmail = "SYAVUYA08@OUTLOOK.COM",
                            NormalizedUserName = "5001015009087",
                            PasswordHash = "AQAAAAIAAYagAAAAEI2RDy0xnXTih006/tyC+SAayEjM6xYFlOhGuwdTpwfpc3Oii6X7cJFhdyWYbU+S+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d672b3c3-1d30-46b2-bde2-11175dac39fb",
                            TwoFactorEnabled = false,
                            UserName = "5001015009087"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasBaseType("Domain.Entities.Identity.ApplicationUser");

                    b.HasDiscriminator().HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4715479e-92d3-4e75-b9fe-a1bfad398b99"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "18220089-d6f2-40ce-b123-6f0aae5e94ca",
                            Email = "Rachel16@yahoo.com",
                            EmailConfirmed = true,
                            FirstName = "Rachel",
                            Gender = 0,
                            LastName = "Singh",
                            LockoutEnabled = false,
                            NormalizedEmail = "RACHEL16@YAHOO.COM",
                            NormalizedUserName = "7203231414080",
                            PasswordHash = "AQAAAAIAAYagAAAAELVtUUpIWDSg6ry1eG44LYQucHYBq/k7zwMbRKpo92uDKlAk0GrW4d1Ycd6CodWgaA==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/781.jpg",
                            SecurityStamp = "ee2f1499-8690-4d14-a88b-60a6b6904403",
                            TwoFactorEnabled = false,
                            UserName = "7203231414080"
                        },
                        new
                        {
                            Id = new Guid("23ac6243-73e9-43f0-afd5-2b79292b9577"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c07d4769-a1ab-4127-ac9d-867e750b9c76",
                            Email = "Erma_Schultz75@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Erma",
                            Gender = 1,
                            LastName = "Schultz",
                            LockoutEnabled = false,
                            MiddleName = "Claudia",
                            NormalizedEmail = "ERMA_SCHULTZ75@HOTMAIL.COM",
                            NormalizedUserName = "9506269295082",
                            PasswordHash = "AQAAAAIAAYagAAAAEL5F+hirTHeGFw+fOoZpNNbgKTNU+xIJQX/SiRdwP69MM423FKxZHI54GY4zRuLm3g==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("c230c7d4-7c47-48bb-b319-13701cc8c52a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/141.jpg",
                            SecurityStamp = "84d7d9ae-7b12-40ad-a66e-98912e31e91d",
                            TwoFactorEnabled = false,
                            UserName = "9506269295082"
                        },
                        new
                        {
                            Id = new Guid("224bbb28-3fac-480c-96af-93f551f2e158"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "215a326e-2dea-4560-8c87-72a3acf1bf35",
                            Email = "Robin.Barrows62@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Robin",
                            Gender = 1,
                            LastName = "Barrows",
                            LockoutEnabled = false,
                            MiddleName = "Kenneth",
                            NormalizedEmail = "ROBIN.BARROWS62@HOTMAIL.COM",
                            NormalizedUserName = "7308095251088",
                            PasswordHash = "AQAAAAIAAYagAAAAEH7a+8iIQMIULB1lpCZCH6svugDKeVDS43o8O4O/rewN38zYQY19nwrXVQVPvztjTw==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/263.jpg",
                            SecurityStamp = "643a8956-509a-4d12-aa98-6afd8442c87b",
                            TwoFactorEnabled = false,
                            UserName = "7308095251088"
                        },
                        new
                        {
                            Id = new Guid("9a789550-511e-41b1-b28e-1f2df764f407"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7a21c5ac-5683-4cd9-9559-ef887f3c53d1",
                            Email = "Terrence14@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Terrence",
                            Gender = 0,
                            LastName = "Nkomo",
                            LockoutEnabled = false,
                            NormalizedEmail = "TERRENCE14@GMAIL.COM",
                            NormalizedUserName = "9904270873080",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuYYuOSeCrnMGODG/OGiAdNOstfA26cGBbiXyzkVw6mcdAlCfDtuHJPeLRxp/kfPQ==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1031.jpg",
                            SecurityStamp = "506f1e28-2ccb-4570-a350-4293525cd33d",
                            TwoFactorEnabled = false,
                            UserName = "9904270873080"
                        },
                        new
                        {
                            Id = new Guid("ca8c5f0b-9dc7-4831-9885-856cb7a35599"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c04ccb0f-71c2-4a03-b935-f8af2a73fb03",
                            Email = "Dan_Motloung63@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Dan",
                            Gender = 1,
                            LastName = "Motloung",
                            LockoutEnabled = false,
                            MiddleName = "Megan",
                            NormalizedEmail = "DAN_MOTLOUNG63@HOTMAIL.COM",
                            NormalizedUserName = "8101077454088",
                            PasswordHash = "AQAAAAIAAYagAAAAEFujLqfYN5xjSDvu7HWTBLXOQB6vY/x9rLR9yB48Lb5Be3ypnWBOQQyaZYsSsDnq0Q==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg",
                            SecurityStamp = "5cfc2669-fb71-4ad0-8be4-60e242eabf0c",
                            TwoFactorEnabled = false,
                            UserName = "8101077454088"
                        },
                        new
                        {
                            Id = new Guid("0d6fe597-26e5-4d4e-a198-be09dfd293c1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "963c5b6d-8ca6-4c94-940e-0a18659ad52f",
                            Email = "Stuart.Adams@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Stuart",
                            Gender = 1,
                            LastName = "Adams",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUART.ADAMS@GMAIL.COM",
                            NormalizedUserName = "0504106744080",
                            PasswordHash = "AQAAAAIAAYagAAAAEN3UA7NuvPe0O0dgE/kxSpSNWU/nqQwgVeTAAAwoiYvYFMbLixZ4T/NM/ESzEyQ0xg==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("a0ee568b-8bf2-41a5-a3d9-a2d4d393d66e"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/967.jpg",
                            SecurityStamp = "fb020ced-bf08-4196-a021-f71970531a13",
                            TwoFactorEnabled = false,
                            UserName = "0504106744080"
                        },
                        new
                        {
                            Id = new Guid("3ca4435c-2e31-46e4-a74e-1cd56a9162ac"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "987eadba-2c9f-424f-98fb-69f4e942aa6a",
                            Email = "Mark.Parnell@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            Gender = 0,
                            LastName = "Parnell",
                            LockoutEnabled = false,
                            MiddleName = "Ana",
                            NormalizedEmail = "MARK.PARNELL@HOTMAIL.COM",
                            NormalizedUserName = "0202272186083",
                            PasswordHash = "AQAAAAIAAYagAAAAEPCdq2GadGEvSX14+DTFfHtrXtyycXBm5ZKanSjWfZfBWApCpESniAdkHJc53jMFOw==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("d1c03637-213a-4fad-bcba-a572988e57f7"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/828.jpg",
                            SecurityStamp = "8837a0b2-e2f8-40cd-a67a-d887ce2c0e57",
                            TwoFactorEnabled = false,
                            UserName = "0202272186083"
                        },
                        new
                        {
                            Id = new Guid("6df22e8a-5c8a-4e93-823d-2a430ee8db23"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2ab9da13-5755-48ef-bb9b-583515f5c49c",
                            Email = "Howard.Gibson64@hotmail.com",
                            EmailConfirmed = true,
                            FirstName = "Howard",
                            Gender = 0,
                            LastName = "Gibson",
                            LockoutEnabled = false,
                            MiddleName = "Samuel",
                            NormalizedEmail = "HOWARD.GIBSON64@HOTMAIL.COM",
                            NormalizedUserName = "8308024085085",
                            PasswordHash = "AQAAAAIAAYagAAAAEKio0YOB0/FUo3kCDm9HlCJzKFTXVdQn8gF6wRAjBKE0eKg5eNLQoEp64UsaOSPR+A==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("c230c7d4-7c47-48bb-b319-13701cc8c52a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/543.jpg",
                            SecurityStamp = "80267d48-1051-4d1b-8bfd-466a5bb429f6",
                            TwoFactorEnabled = false,
                            UserName = "8308024085085"
                        },
                        new
                        {
                            Id = new Guid("b67d2aea-d09e-41f0-a2e4-dadd9d22a18c"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e2af3ba3-7f00-4dfd-af9a-e1e98fdbcc2a",
                            Email = "Justin.Poore@yahoo.com",
                            EmailConfirmed = true,
                            FirstName = "Justin",
                            Gender = 1,
                            LastName = "Poore",
                            LockoutEnabled = false,
                            MiddleName = "Warren",
                            NormalizedEmail = "JUSTIN.POORE@YAHOO.COM",
                            NormalizedUserName = "7907065098088",
                            PasswordHash = "AQAAAAIAAYagAAAAEJsLwTU0qjAz+8pumylojlAFaZ6Dem7+YP5iBCpt/5arcD8uYUwOOwcAxVtpEQkUEA==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("d1c03637-213a-4fad-bcba-a572988e57f7"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1094.jpg",
                            SecurityStamp = "02e97d47-fbfb-40d2-a68a-122fd14ef727",
                            TwoFactorEnabled = false,
                            UserName = "7907065098088"
                        },
                        new
                        {
                            Id = new Guid("8e7a5a23-74c0-4947-bbfe-03d15315ff6d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "821069fb-5ad3-4840-ae12-f7efc2a282b6",
                            Email = "Lindsay40@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Lindsay",
                            Gender = 1,
                            LastName = "Zimmerman",
                            LockoutEnabled = false,
                            NormalizedEmail = "LINDSAY40@GMAIL.COM",
                            NormalizedUserName = "0202275146084",
                            PasswordHash = "AQAAAAIAAYagAAAAEG2izPP3cNz4qZNa2Hde3QcI+FVrCKtFXqtpVm85vXdcjBsu5UENMs+Kc29Oo9Yp4Q==",
                            PhoneNumberConfirmed = false,
                            PhysicalAddressId = new Guid("4aabe8c0-1742-46f1-9653-b9b4b9c6894a"),
                            ProfileImageUrl = "https://ipfs.io/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/230.jpg",
                            SecurityStamp = "4379ced4-d0c9-4952-8985-6a9c017377f6",
                            TwoFactorEnabled = false,
                            UserName = "0202275146084"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Domain.Entities.Document", b =>
                {
                    b.HasBaseType("Domain.Entities.Resource");

                    b.Property<int?>("PageCount")
                        .HasColumnType("int");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.HasBaseType("Domain.Entities.Resource");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Domain.Entities.Video", b =>
                {
                    b.HasBaseType("Domain.Entities.Resource");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("Domain.Entities.Identity.UserRoleLink", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoleLinks");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("fd6ebe91-e83e-42e1-be3e-07ba2f25236b"),
                            RoleId = new Guid("00edafe3-b047-5980-d0fa-da10f400c1e5")
                        },
                        new
                        {
                            UserId = new Guid("4715479e-92d3-4e75-b9fe-a1bfad398b99"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("23ac6243-73e9-43f0-afd5-2b79292b9577"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("224bbb28-3fac-480c-96af-93f551f2e158"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("9a789550-511e-41b1-b28e-1f2df764f407"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("ca8c5f0b-9dc7-4831-9885-856cb7a35599"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("0d6fe597-26e5-4d4e-a198-be09dfd293c1"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("3ca4435c-2e31-46e4-a74e-1cd56a9162ac"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("6df22e8a-5c8a-4e93-823d-2a430ee8db23"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("b67d2aea-d09e-41f0-a2e4-dadd9d22a18c"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        },
                        new
                        {
                            UserId = new Guid("8e7a5a23-74c0-4947-bbfe-03d15315ff6d"),
                            RoleId = new Guid("9dfe9b8f-4513-7c23-b3b2-b205864da075")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Employer", b =>
                {
                    b.HasOne("Domain.Entities.PhysicalAddress", "PhysicalAddress")
                        .WithMany()
                        .HasForeignKey("PhysicalAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("PhysicalAddress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.HasOne("Domain.Entities.PhysicalAddress", "PhysicalAddress")
                        .WithMany()
                        .HasForeignKey("PhysicalAddressId");

                    b.Navigation("PhysicalAddress");
                });

            modelBuilder.Entity("Domain.Entities.Identity.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.HasOne("Domain.Entities.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId");

                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "PostedByUser")
                        .WithMany()
                        .HasForeignKey("PostedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PhysicalAddress", "WorkLocationAddress")
                        .WithMany()
                        .HasForeignKey("WorkLocationAddressId");

                    b.Navigation("Employer");

                    b.Navigation("PostedByUser");

                    b.Navigation("WorkLocationAddress");
                });

            modelBuilder.Entity("Domain.Entities.JobApplication", b =>
                {
                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.JobAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithMany("JobAssignments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Resource", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "VerifiedByUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByUserId");

                    b.Navigation("UploadedByUser");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Domain.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.HasOne("Domain.Entities.Resource", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Image", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Video", b =>
                {
                    b.HasOne("Domain.Entities.Resource", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Video", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Identity.UserRoleLink", b =>
                {
                    b.HasOne("Domain.Entities.Identity.Role", "Role")
                        .WithMany("UserRoleLinks")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoleLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Identity.UserRoleLink", "UserId", "RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoleLinks");
                });

            modelBuilder.Entity("Domain.Entities.Identity.Role", b =>
                {
                    b.Navigation("UserRoleLinks");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Navigation("JobApplications");

                    b.Navigation("JobAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
